# Generated by Django 3.0.6 on 2020-07-20 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_no', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Payment_date', models.DateField(default=datetime.date(2020, 7, 20))),
                ('Enquiry_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('Enquiry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=250)),
                ('Qualification', models.CharField(max_length=50)),
                ('College', models.CharField(max_length=150)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Enquiry_date', models.DateField(default=datetime.date(2020, 7, 20))),
                ('Followup_date', models.DateField()),
                ('Status', models.CharField(choices=[('1', 'Call_Back'), ('2', 'Admitted'), ('3', 'Cancel')], max_length=20)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiry.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.CharField(max_length=150, unique=True)),
                ('Date', models.DateField()),
                ('Status', models.CharField(choices=[('1', 'Yet to Begin'), ('2', 'Started'), ('3', 'Completed')], max_length=100)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiry.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_no', models.CharField(max_length=100, unique=True)),
                ('Enquiry_id', models.CharField(max_length=100)),
                ('Course_fee', models.IntegerField(max_length=50)),
                ('Date', models.DateField(default=datetime.date(2020, 7, 20))),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquiry.Batch')),
            ],
        ),
    ]
