# Generated by Django 3.0.6 on 2020-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0002_enquiry_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Course_fee',
            field=models.IntegerField(),
        ),
    ]
