# Generated by Django 3.0.6 on 2020-07-23 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0003_auto_20200720_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counceller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counceller_name', models.CharField(max_length=150)),
                ('Contact', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='admission',
            name='Date',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Enquiry_date',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_date',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
    ]
