# Generated by Django 3.0.6 on 2020-07-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Enquiry', '0006_enquiry_counceller'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='Source',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Enquiry.Source'),
            preserve_default=False,
        ),
    ]
